version: '3.8'
services:
  db:
    image: postgres:16.2
  restart: always
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password
  ports:
    - '5432:5432'
  volumes:
    - db:/var/lib/postgresql/data
    - ./db/init.sql:/docker-entrypoint-initdb.d/plants.pgsql

volumes:
  db:
    driver: local