import psycopg2 as psy

conn = psy.connect('dbname=postgres user=postgres password=password host=0.0.0.0 port=30420')
cur = conn.cursor()

raw = "ACANTHACEAE ACORACEAE ADOXACEAE AGAVACEAE AIZOACEAE ALISMATACEAE ALLIACEAE ALTINGIACEAE AMARANTHACEAE AMARYLLIDACEAE ANACARDIACEAE ANNONACEAE APIACEAE APOCYNACEAE AQUIFOLIACEAE ARACEAE ARALIACEAE ARECACEAE ARISTOLOCHIACEAE ASPARAGACEAE ASPLENIACEAE ASTERACEAE AZOLLACEAE BALSAMINACEAE BERBERIDACEAE BETULACEAE BIGNONIACEAE BLECHNACEAE BORAGINACEAE BRASSICACEAE BROMELIACEAE BURMANNIACEAE CABOMBACEAE CACTACEAE CAMPANULACEAE CANNABACEAE CAPRIFOLIACEAE CARYOPHYLLACEAE CELASTRACEAE CERATOPHYLLACEAE CHENOPODIACEAE CISTACEAE CLEOMACEAE COLCHICACEAE COMMELINACEAE CONVOLVULACEAE CORNACEAE CRASSULACEAE CUCURBITACEAE CUPRESSACEAE CYPERACEAE DENNSTAEDTIACEAE DIOSCOREACEAE DIPSACACEAE DROSERACEAE DRYOPTERIDACEAE EBENACEAE ELAEAGNACEAE ELATINACEAE EQUISETACEAE ERICACEAE ERIOCAULACEAE EUPHORBIACEAE FABACEAE FAGACEAE GELSEMIACEAE GENTIANACEAE GERANIACEAE GROSSULARIACEAE HALORAGACEAE HAMAMELIDACEAE HEMEROCALLIDACEAE HYACINTHACEAE HYDRANGEACEAE HYDROCHARITACEAE HYDROLEACEAE HYMENOPHYLLACEAE HYPERICACEAE HYPOXIDACEAE IRIDACEAE ISOETACEAE ITEACEAE JUGLANDACEAE JUNCACEAE LAMIACEAE LAURACEAE LENTIBULARIACEAE LILIACEAE LINACEAE LINDERNIACEAE LOASACEAE LOGANIACEAE LOMARIOPSIDACEAE LYCOPODIACEAE LYGODIACEAE LYTHRACEAE MAGNOLIACEAE MALVACEAE MARANTACEAE MARSILEACEAE MARTYNIACEAE MELANTHIACEAE MELASTOMATACEAE MELIACEAE MENISPERMACEAE MENYANTHACEAE MOLLUGINACEAE MORACEAE MYRICACEAE MYRSINACEAE NARTHECIACEAE NELUMBONACEAE NYCTAGINACEAE NYMPHAEACEAE NYSSACEAE OLEACEAE ONAGRACEAE ONOCLEACEAE OPHIOGLOSSACEAE ORCHIDACEAE OROBANCHACEAE OSMUNDACEAE OXALIDACEAE PAPAVERACEAE PARNASSIACEAE PASSIFLORACEAE PAULOWNIACEAE PENTHORACEAE PHRYMACEAE PHYLLANTHACEAE PHYTOLACCACEAE PINACEAE PLANTAGINACEAE PLATANACEAE POACEAE PODOSTEMACEAE POLEMONIACEAE POLYGALACEAE POLYGONACEAE POLYPODIACEAE PONTEDERIACEAE PORTULACACEAE POTAMOGETONACEAE PRIMULACEAE PSILOTACEAE PTERIDACEAE RANUNCULACEAE RHAMNACEAE ROSACEAE RUBIACEAE RUSCACEAE RUTACEAE SALICACEAE SALVINIACEAE SANTALACEAE SAPINDACEAE SAPOTACEAE SAURURACEAE SAXIFRAGACEAE SCHISANDRACEAE SCROPHULARIACEAE SELAGINELLACEAE SIMAROUBACEAE SMILACACEAE SOLANACEAE SPHENOCLEACEAE STAPHYLEACEAE STYRACACEAE SYMPLOCACEAE TAMARICACEAE TETRACHONDRACEAE THEACEAE THELYPTERIDACEAE THEMIDACEAE THEOPHRASTACEAE THYMELAEACEAE TRILLIACEAE TYPHACEAE ULMACEAE URTICACEAE VALERIANACEAE VERBENACEAE VIOLACEAE VITACEAE WOODSIACEAE XYRIDACEAE ZYGOPHYLLACEAE"
family_list = raw.split(" ")
cur.execute("SELECT family FROM ar_plants.family;")
db_family_list = cur.fetchall()

for _ in range(len(db_family_list)):
    if db_family_list[_][0] in family_list:
        continue
    else:
        print("MISSING " + db_family_list[_][0])



